### ISSUE TITLE
[0.10.1] Getting "panic: assignment to entry in nil map" when using env variable assignment

### ISSUE THREAD

**Issue by x-jokay** [aler9/rtsp-simple-server#103]
## Which version are you using?

v0.10.1

## Which operating system are you using?

Linux

## Question

These vars work as expected:

- RTSP_PROTOCOLS
- RTSP_RTSPPORT
- RTSP_RTPPORT
- RTSP_RTCPPORT
- RTSP_READTIMEOUT
- RTSP_WRITETIMEOUT

But as soon as I try to use one of the following I get the exception message:

- RTSP_PATHS_ALL_READUSER
- RTSP_PATHS_ALL_READPASS
- RTSP_PATHS_CAM1_SOURCE
- RTSP_PATHS_CAM1_SOURCEPROTOCOL
- RTSP_PATHS_CAM1_SOURCEONDEMAND

```sh
panic: assignment to entry in nil map

goroutine 1 [running]:
reflect.mapassign(0x8c65a0, 0x0, 0xc000097200, 0xc0000933a8)
	/usr/local/go/src/runtime/map.go:1319 +0x3f
reflect.Value.SetMapIndex(0x8c65a0, 0xc00009bfa0, 0x195, 0x8a03c0, 0xc000097200, 0x98, 0x889b60, 0xc0000b0a20, 0x16)
	/usr/local/go/src/reflect/value.go:1681 +0x267
github.com/aler9/rtsp-simple-server/confenv.process(0xc000093a30, 0xc0000b6b30, 0xa, 0x8c65a0, 0xc00009bfa0, 0x195, 0x195, 0xc0000b6b30)
	/s/confenv/confenv.go:88 +0x684
github.com/aler9/rtsp-simple-server/confenv.process(0xc000093a30, 0x95047e, 0x4, 0x93a0a0, 0xc00009bee0, 0x199, 0xc0000ac760, 0x2)
	/s/confenv/confenv.go:109 +0xdf3
github.com/aler9/rtsp-simple-server/confenv.Process(0x95047e, 0x4, 0x8be3e0, 0xc00009bee0, 0x0, 0x0)
	/s/confenv/confenv.go:127 +0x240
github.com/aler9/rtsp-simple-server/conf.Load(0x95c713, 0x16, 0x0, 0x0, 0x0)
	/s/conf/conf.go:136 +0xb7
main.newProgram(0xc0000961b0, 0x0, 0x0, 0x405aaf, 0xc000094058, 0x0)
	/s/main.go:77 +0x44d
main.main()
	/s/main.go:402 +0x6c
panic: assignment to entry in nil map

goroutine 1 [running]:
reflect.mapassign(0x8c65a0, 0x0, 0xc00020a1e0, 0xc00004d3a8)
	/usr/local/go/src/runtime/map.go:1319 +0x3f
reflect.Value.SetMapIndex(0x8c65a0, 0xc000200740, 0x195, 0x8a03c0, 0xc00020a1e0, 0x98, 0x889b60, 0xc000220120, 0x16)
	/usr/local/go/src/reflect/value.go:1681 +0x267
github.com/aler9/rtsp-simple-server/confenv.process(0xc00004da30, 0xc00020c1d0, 0xa, 0x8c65a0, 0xc000200740, 0x195, 0x195, 0xc00020c1d0)
	/s/confenv/confenv.go:88 +0x684
github.com/aler9/rtsp-simple-server/confenv.process(0xc00004da30, 0x95047e, 0x4, 0x93a0a0, 0xc000200680, 0x199, 0xc0002082c0, 0x2)
	/s/confenv/confenv.go:109 +0xdf3
github.com/aler9/rtsp-simple-server/confenv.Process(0x95047e, 0x4, 0x8be3e0, 0xc000200680, 0x0, 0x0)
	/s/confenv/confenv.go:127 +0x240
github.com/aler9/rtsp-simple-server/conf.Load(0x95c713, 0x16, 0x0, 0x0, 0x0)
	/s/conf/conf.go:136 +0xb7
main.newProgram(0xc00001e1d0, 0x0, 0x0, 0x405aaf, 0xc00002c0b8, 0x0)
	/s/main.go:77 +0x44d
main.main()
	/s/main.go:402 +0x6c
panic: assignment to entry in nil map

goroutine 1 [running]:
reflect.mapassign(0x8c65a0, 0x0, 0xc00001f220, 0xc00004d3a8)
	/usr/local/go/src/runtime/map.go:1319 +0x3f
reflect.Value.SetMapIndex(0x8c65a0, 0xc0001540c0, 0x195, 0x8a03c0, 0xc00001f220, 0x98, 0x889b60, 0xc000020b40, 0x16)
	/usr/local/go/src/reflect/value.go:1681 +0x267
github.com/aler9/rtsp-simple-server/confenv.process(0xc00004da30, 0xc000024b60, 0xa, 0x8c65a0, 0xc0001540c0, 0x195, 0x195, 0xc000024b60)
	/s/confenv/confenv.go:88 +0x684
github.com/aler9/rtsp-simple-server/confenv.process(0xc00004da30, 0x95047e, 0x4, 0x93a0a0, 0xc000154000, 0x199, 0xc00000c7a0, 0x2)
	/s/confenv/confenv.go:109 +0xdf3
github.com/aler9/rtsp-simple-server/confenv.Process(0x95047e, 0x4, 0x8be3e0, 0xc000154000, 0x0, 0x0)
	/s/confenv/confenv.go:127 +0x240
github.com/aler9/rtsp-simple-server/conf.Load(0x95c713, 0x16, 0x0, 0x0, 0x0)
	/s/conf/conf.go:136 +0xb7
main.newProgram(0xc00001e1d0, 0x0, 0x0, 0x405aaf, 0xc00002c0b8, 0x0)
	/s/main.go:77 +0x44d
main.main()
	/s/main.go:402 +0x6c
panic: assignment to entry in nil map

goroutine 1 [running]:
reflect.mapassign(0x8c65a0, 0x0, 0xc00001e240, 0xc00008d3a8)
	/usr/local/go/src/runtime/map.go:1319 +0x3f
reflect.Value.SetMapIndex(0x8c65a0, 0xc000074740, 0x195, 0x8a03c0, 0xc00001e240, 0x98, 0x889b60, 0xc000020360, 0x16)
	/usr/local/go/src/reflect/value.go:1681 +0x267
github.com/aler9/rtsp-simple-server/confenv.process(0xc00008da30, 0xc000024200, 0xa, 0x8c65a0, 0xc000074740, 0x195, 0x195, 0xc000024200)
	/s/confenv/confenv.go:88 +0x684
github.com/aler9/rtsp-simple-server/confenv.process(0xc00008da30, 0x95047e, 0x4, 0x93a0a0, 0xc000074680, 0x199, 0xc00000c360, 0x2)
	/s/confenv/confenv.go:109 +0xdf3
github.com/aler9/rtsp-simple-server/confenv.Process(0x95047e, 0x4, 0x8be3e0, 0xc000074680, 0x0, 0x0)
	/s/confenv/confenv.go:127 +0x240
github.com/aler9/rtsp-simple-server/conf.Load(0x95c713, 0x16, 0x0, 0x0, 0x0)
	/s/conf/conf.go:136 +0xb7
main.newProgram(0xc0001041b0, 0x0, 0x0, 0x405aaf, 0xc000102058, 0x0)
	/s/main.go:77 +0x44d
main.main()
	/s/main.go:402 +0x6c
panic: assignment to entry in nil map

goroutine 1 [running]:
reflect.mapassign(0x8c65a0, 0x0, 0xc0002101e0, 0xc0000933a8)
	/usr/local/go/src/runtime/map.go:1319 +0x3f
reflect.Value.SetMapIndex(0x8c65a0, 0xc00020a740, 0x195, 0x8a03c0, 0xc0002101e0, 0x98, 0x889b60, 0xc000222120, 0x16)
	/usr/local/go/src/reflect/value.go:1681 +0x267
github.com/aler9/rtsp-simple-server/confenv.process(0xc000093a30, 0xc0002121d0, 0xa, 0x8c65a0, 0xc00020a740, 0x195, 0x195, 0xc0002121d0)
	/s/confenv/confenv.go:88 +0x684
github.com/aler9/rtsp-simple-server/confenv.process(0xc000093a30, 0x95047e, 0x4, 0x93a0a0, 0xc00020a680, 0x199, 0xc0002002e0, 0x2)
	/s/confenv/confenv.go:109 +0xdf3
github.com/aler9/rtsp-simple-server/confenv.Process(0x95047e, 0x4, 0x8be3e0, 0xc00020a680, 0x0, 0x0)
	/s/confenv/confenv.go:127 +0x240
github.com/aler9/rtsp-simple-server/conf.Load(0x95c713, 0x16, 0x0, 0x0, 0x0)
	/s/conf/conf.go:136 +0xb7
main.newProgram(0xc0000961b0, 0x0, 0x0, 0x405aaf, 0xc000094058, 0x0)
	/s/main.go:77 +0x44d
main.main()
	/s/main.go:402 +0x6c
panic: assignment to entry in nil map

goroutine 1 [running]:
reflect.mapassign(0x8c65a0, 0x0, 0xc0002121e0, 0xc0000933a8)
	/usr/local/go/src/runtime/map.go:1319 +0x3f
reflect.Value.SetMapIndex(0x8c65a0, 0xc00020c740, 0x195, 0x8a03c0, 0xc0002121e0, 0x98, 0x889b60, 0xc000222120, 0x16)
	/usr/local/go/src/reflect/value.go:1681 +0x267
github.com/aler9/rtsp-simple-server/confenv.process(0xc000093a30, 0xc0002001d0, 0xa, 0x8c65a0, 0xc00020c740, 0x195, 0x195, 0xc0002001d0)
	/s/confenv/confenv.go:88 +0x684
github.com/aler9/rtsp-simple-server/confenv.process(0xc000093a30, 0x95047e, 0x4, 0x93a0a0, 0xc00020c680, 0x199, 0xc0002062e0, 0x2)
	/s/confenv/confenv.go:109 +0xdf3
github.com/aler9/rtsp-simple-server/confenv.Process(0x95047e, 0x4, 0x8be3e0, 0xc00020c680, 0x0, 0x0)
	/s/confenv/confenv.go:127 +0x240
github.com/aler9/rtsp-simple-server/conf.Load(0x95c713, 0x16, 0x0, 0x0, 0x0)
	/s/conf/conf.go:136 +0xb7
main.newProgram(0xc00009e1b0, 0x0, 0x0, 0x405aaf, 0xc00009c058, 0x0)
	/s/main.go:77 +0x44d
main.main()
	/s/main.go:402 +0x6c
panic: assignment to entry in nil map

goroutine 1 [running]:
reflect.mapassign(0x8c65a0, 0x0, 0xc0002101e0, 0xc00008d3a8)
	/usr/local/go/src/runtime/map.go:1319 +0x3f
reflect.Value.SetMapIndex(0x8c65a0, 0xc00020a740, 0x195, 0x8a03c0, 0xc0002101e0, 0x98, 0x889b60, 0xc000222240, 0x16)
	/usr/local/go/src/reflect/value.go:1681 +0x267
github.com/aler9/rtsp-simple-server/confenv.process(0xc00008da30, 0xc0002121d0, 0xa, 0x8c65a0, 0xc00020a740, 0x195, 0x195, 0xc0002121d0)
	/s/confenv/confenv.go:88 +0x684
github.com/aler9/rtsp-simple-server/confenv.process(0xc00008da30, 0x95047e, 0x4, 0x93a0a0, 0xc00020a680, 0x199, 0xc0002002e0, 0x2)
	/s/confenv/confenv.go:109 +0xdf3
github.com/aler9/rtsp-simple-server/confenv.Process(0x95047e, 0x4, 0x8be3e0, 0xc00020a680, 0x0, 0x0)
	/s/confenv/confenv.go:127 +0x240
github.com/aler9/rtsp-simple-server/conf.Load(0x95c713, 0x16, 0x0, 0x0, 0x0)
	/s/conf/conf.go:136 +0xb7
main.newProgram(0xc0001041b0, 0x0, 0x0, 0x405aaf, 0xc000102058, 0x0)
	/s/main.go:77 +0x44d
main.main()
	/s/main.go:402 +0x6c
```

It should correspond to this config:

```yml
protocols: [ udp,tcp ]
rtspPort: 50000
rtpPort: 50001
rtcpPort: 50002
readTimeout: 15s
writeTimeout: 15s

paths:
  all:
    readUser: testUser
    readPass: testPassword
  cam1:
    source: rtsp://camUser:camPassword@192.168.1.120:554/s0
    sourceProtocol: udp
    sourceOnDemand: yes
```

**Comment by aler9** [comment]
Hello, thanks for reporting the bug, this wasn't detected by tests since it happens when the config file is missing (but since it's optional, this shouldn't happen).

**Comment by x-jokay** [comment]
Thx for the fix. Once `0.10.2` is released, I can finally delete [my](https://github.com/x-jokay/docker-rtsp-simple-server) Docker container and use yours with env params 😉

**Comment by aler9** [comment]
added in v0.11.0
