### ISSUE TITLE
GO memory Leak

### ISSUE THREAD

**Issue by brennanwilkes** [aler9/rtsp-simple-server#1077]
## Which version are you using?

v0.17.14

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [x] Linux arm7 Docker
- [ ] Linux arm6 standard
- [x] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

After running the server for 2-3 days, whilst publishing a live stream, the server crashes with what looks like a GO memory leak. We're using a slightly older version, as we found upgrading to the latest severely increased our stream latency, likely related to hardware constraints. 

## Describe how to replicate the issue

1. start the server
2. publish a stream with ffmpeg
3. Wait 2-3 days of runtime

## Did you attach the server logs?

yes:

```
[Logs]    [8/7/2022, 11:14:33 PM] [stream-server] 
[Logs]    [8/7/2022, 11:14:33 PM] [stream-server] goroutine 44 [running]:
[Logs]    [8/7/2022, 11:14:33 PM] [stream-server] bytes.(*Buffer).grow(0x2546090, 0x1)
[Logs]    [8/7/2022, 11:14:33 PM] [stream-server] 	/usr/local/go/src/bytes/buffer.go:139 +0x270
[Logs]    [8/7/2022, 11:14:33 PM] [stream-server] bytes.(*Buffer).Write(0x2546090, {0x241aa51, 0x1, 0x1})
[Logs]    [8/7/2022, 11:14:33 PM] [stream-server] 	/usr/local/go/src/bytes/buffer.go:172 +0x54
[Logs]    [8/7/2022, 11:14:33 PM] [stream-server] github.com/aler9/rtsp-simple-server/internal/hls.(*muxerTSSegment).write(...)
[Logs]    [8/7/2022, 11:14:33 PM] [stream-server] 	/s/internal/hls/muxer_ts_segment.go:50
[Logs]    [8/7/2022, 11:14:33 PM] [stream-server] github.com/aler9/rtsp-simple-server/internal/hls.(*muxerTSWriter).Write(0x240e538, {0x241aa51, 0x1, 0x1})
[Logs]    [8/7/2022, 11:14:33 PM] [stream-server] 	/s/internal/hls/muxer_ts_writer.go:46 +0x40
[Logs]    [8/7/2022, 11:14:33 PM] [stream-server] github.com/asticode/go-astikit.(*BitsWriter).flushBsCache(0x249a4e0)
[Logs]    [8/7/2022, 11:14:33 PM] [stream-server] 	/go/pkg/mod/github.com/asticode/go-astikit@v0.20.0/binary.go:144 +0x40
[Logs]    [8/7/2022, 11:14:33 PM] [stream-server] github.com/asticode/go-astikit.(*BitsWriter).writeFullByte(0x249a4e0, 0xb7)
[Logs]    [8/7/2022, 11:14:33 PM] [stream-server] 	/go/pkg/mod/github.com/asticode/go-astikit@v0.20.0/binary.go:162 +0x7c
[Logs]    [8/7/2022, 11:14:33 PM] [stream-server] github.com/asticode/go-astikit.(*BitsWriter).Write(0x249a4e0, {0x5d73b8, 0x255db0c})
[Logs]    [8/7/2022, 11:14:33 PM] [stream-server] 	/go/pkg/mod/github.com/asticode/go-astikit@v0.20.0/binary.go:76 +0x2d4
[Logs]    [8/7/2022, 11:14:33 PM] [stream-server] github.com/asticode/go-astits.writePacket(0x249a4e0, 0x255db7c, 0xbc)
[Logs]    [8/7/2022, 11:14:33 PM] [stream-server] 	/go/pkg/mod/github.com/asticode/go-astits@v1.10.0/packet.go:347 +0x124
[Logs]    [8/7/2022, 11:14:33 PM] [stream-server] github.com/asticode/go-astits.(*Muxer).WriteData(0x26ce790, 0x255dcf8)
[Logs]    [8/7/2022, 11:14:33 PM] [stream-server] 	/go/pkg/mod/github.com/asticode/go-astits@v1.10.0/muxer.go:251 +0x5c8
[Logs]    [8/7/2022, 11:14:33 PM] [stream-server] github.com/aler9/rtsp-simple-server/internal/hls.(*muxerTSWriter).WriteData(...)
[Logs]    [8/7/2022, 11:14:33 PM] [stream-server] 	/s/internal/hls/muxer_ts_writer.go:50
[Logs]    [8/7/2022, 11:14:33 PM] [stream-server] github.com/aler9/rtsp-simple-server/internal/hls.(*muxerTSSegment).writeH264(0x2546080, {0xc0b3bc05e4471960, 0x7e8fd615b6, 0xa7d520}, 0xffffc84127c67611, 0xffffc84133b23811, 0x1, {0x2e1e000, 0x1a0c7, 0x1c000})
[Logs]    [8/7/2022, 11:14:33 PM] [stream-server] 	/s/internal/hls/muxer_ts_segment.go:101 +0x5e4
[Logs]    [8/7/2022, 11:14:33 PM] [stream-server] github.com/aler9/rtsp-simple-server/internal/hls.(*muxerTSGenerator).writeH264(0x24c27d0, 0xffffc84115e4d311, {0x2686240, 0x1, 0x1})
[Logs]    [8/7/2022, 11:14:33 PM] [stream-server] 	/s/internal/hls/muxer_ts_generator.go:120 +0x3b0
[Logs]    [8/7/2022, 11:14:33 PM] [stream-server] github.com/aler9/rtsp-simple-server/internal/hls.(*Muxer).WriteH264(...)
[Logs]    [8/7/2022, 11:14:33 PM] [stream-server] 	/s/internal/hls/muxer.go:70
[Logs]    [8/7/2022, 11:14:33 PM] [stream-server] github.com/aler9/rtsp-simple-server/internal/core.(*hlsMuxer).runInner.func2.1(0x24b02a0, 0x25940d8, 0x0, 0x249a450, 0x0, 0xffffffff, 0x0)
[Logs]    [8/7/2022, 11:14:33 PM] [stream-server] 	/s/internal/core/hls_muxer.go:362 +0x494
[Logs]    [8/7/2022, 11:14:33 PM] [stream-server] github.com/aler9/rtsp-simple-server/internal/core.(*hlsMuxer).runInner.func2(0x2420a40, 0x24b02a0, 0x25940d8, 0x0, 0x249a450, 0x0, 0xffffffff, 0x0)
[Logs]    [8/7/2022, 11:14:33 PM] [stream-server] 	/s/internal/core/hls_muxer.go:388 +0x4c
[Logs]    [8/7/2022, 11:14:33 PM] [stream-server] created by github.com/aler9/rtsp-simple-server/internal/core.(*hlsMuxer).runInner
[Logs]    [8/7/2022, 11:14:33 PM] [stream-server] 	/s/internal/core/hls_muxer.go:336 +0x61c
[Logs]    [8/7/2022, 11:14:34 PM] Service exited 'stream-server sha256:a3edd4ae709093aba596f9866b268519381c770a2c406a1007ec27b4a94736b2'
```

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Hello, unfortunately we don't have the manpower to support older versions. Anyway, newer versions support [Low-latency HLS](https://github.com/aler9/rtsp-simple-server#low-latency-variant). If you're interested in low latency, HLS and constrained hardware i strongly suggest you to try it.
