### ISSUE TITLE
rtsp source ERR: sdp: invalid syntax `b=RR:0` when relaying VLC RTSP server (live555)

### ISSUE THREAD

**Issue by arkanoid87** [aler9/rtsp-simple-server#115]
## Which version are you using?

v0.12.0

## Which operating system are you using?

Linux

## Describe the problem

this vlc server
`
cvlc -I dummy -vvv myfile.ts --play-and-exit --file-caching=0 --sout='#rtp{sdp=rtsp://:554/stream}' --no-sout-all --sout-keep
`

generates an sdp that contains incompatible syntax:
```
Nov 07 07:06:09 5c2b68da rec[7329]: v=0
Nov 07 07:06:09 5c2b68da rec[7329]: o=- 16379793953309178445 16379793953309178445 IN IP4 5c2b68da
Nov 07 07:06:09 5c2b68da rec[7329]: s=Unnamed
Nov 07 07:06:09 5c2b68da rec[7329]: i=N/A
Nov 07 07:06:09 5c2b68da rec[7329]: c=IN IP4 0.0.0.0
Nov 07 07:06:09 5c2b68da rec[7329]: t=0 0
Nov 07 07:06:09 5c2b68da rec[7329]: a=tool:vlc 3.0.11
Nov 07 07:06:09 5c2b68da rec[7329]: a=recvonly
Nov 07 07:06:09 5c2b68da rec[7329]: a=type:broadcast
Nov 07 07:06:09 5c2b68da rec[7329]: a=charset:UTF-8
Nov 07 07:06:09 5c2b68da rec[7329]: m=audio 0 RTP/AVP 96
Nov 07 07:06:09 5c2b68da rec[7329]: b=RR:0
Nov 07 07:06:09 5c2b68da rec[7329]: a=rtpmap:96 mpeg4-generic/22050
Nov 07 07:06:09 5c2b68da rec[7329]: a=fmtp:96 streamtype=5; profile-level-id=15; mode=AAC-hbr; config=1388; SizeLength=13; IndexLength=3; IndexDeltaLength=3; Profile=1;                                          
Nov 07 07:06:09 5c2b68da rec[7329]: m=video 0 RTP/AVP 96
Nov 07 07:06:09 5c2b68da rec[7329]: b=RR:0
Nov 07 07:06:09 5c2b68da rec[7329]: a=rtpmap:96 H264/90000
Nov 07 07:06:09 5c2b68da rec[7329]: a=fmtp:96 packetization-mode=1;profile-level-id=640028;sprop-parameter-sets=J2QAKKwrQCgDzQDxImo=,KO4CXLA=;
```

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Hello, thanks for reporting the issue, this SDP is now fully supported in master and will be supported in next release.

**Comment by arkanoid87** [comment]
I've compiled master to test your commit. Now it accepts vlc as input, but it crash as soon as I connect the client I'm working with.

I've just downloaded the source and "go build ."

```
$ ./simple_server
2020/11/09 02:16:38 [0/0/0] rtsp-simple-server v0.0.0
2020/11/09 02:16:38 [0/0/0] [UDP/RTP server] opened on :8000
2020/11/09 02:16:38 [0/0/0] [UDP/RTCP server] opened on :8001
2020/11/09 02:16:38 [0/0/0] [TCP server] opened on :8554
2020/11/09 02:16:38 [0/0/0] [path stream] rtsp source started
2020/11/09 02:16:38 [0/0/0] [path stream] connecting to rtsp source
2020/11/09 02:16:38 [0/0/0] [path stream] rtsp source ready
2020/11/09 02:16:38 [1/0/0] [client 10.4.3.1:26880] connected
2020/11/09 02:16:38 [1/0/0] [client 10.4.3.1:26880] DESCRIBE
2020/11/09 02:16:38 [1/0/0] [client 10.4.3.1:26880] SETUP
2020/11/09 02:16:38 [1/0/0] [client 10.4.3.1:26880] PLAY
2020/11/09 02:16:38 [1/0/1] [client 10.4.3.1:26880] is reading from path 'stream', 1 track with tcp
2020/11/09 02:16:43 [1/0/1] [client 10.4.3.1:26880] GET_PARAMETER
2020/11/09 02:16:46 [2/0/1] [client 10.4.3.1:26896] connected
2020/11/09 02:16:46 [2/0/1] [client 10.4.3.1:26896] DESCRIBE
2020/11/09 02:16:46 [2/0/1] [client 10.4.3.1:26896] SETUP
2020/11/09 02:16:46 [2/0/1] [client 10.4.3.1:26896] PLAY
2020/11/09 02:16:46 [2/0/2] [client 10.4.3.1:26896] is reading from path 'stream', 1 track with tcp
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2a7858]

goroutine 22 [running]:
github.com/aler9/gortsplib.(*ConnClient).WriteFrame(...)
        /home/pi/go/pkg/mod/github.com/aler9/gortsplib@v0.0.0-20201108190150-2deddcffab35/connclient.go:265                                                                                                       
github.com/aler9/gortsplib.(*ConnClient).Play.func1(0x1c72b40)
        /home/pi/go/pkg/mod/github.com/aler9/gortsplib@v0.0.0-20201108190150-2deddcffab35/connclient.go:703 +0xe0                                                                                                 
created by github.com/aler9/gortsplib.(*ConnClient).Play
        /home/pi/go/pkg/mod/github.com/aler9/gortsplib@v0.0.0-20201108190150-2deddcffab35/connclient.go:689 +0x2d0     
```

**Comment by aler9** [comment]
Thanks for reporting the crash, it has been fixed too.

**Comment by arkanoid87** [comment]
I've compiled and tested your commit and now crash is gone and audio + video works nicely! Thanks!

It could be unrelated to this issue, but it seems that simple-rtsp-server is not sending keepalives (or any RTSP command) to source vlc server in time and [--rtsp-timeout (60 by default)](https://wiki.videolan.org/VLC_command-line_help) is hit and TEARDOWN is sent from server to client.
 
From my experiments it seems that RTSP GET_PARAMETER works for vlc, but it seems [an hot topic](https://trac.videolan.org/vlc/ticket/22568).

**Comment by aler9** [comment]
I've noticed it too, and that's the reason why i'm delaying the release of the new version.

**Comment by aler9** [comment]
the timeout has been fixed too.

**Comment by aler9** [comment]
added in v0.12.1
