### ISSUE TITLE
Larix Broadcaster for Android fails to publish

### ISSUE THREAD

**Issue by WMSPanel** [aler9/rtsp-simple-server#134]
## Which version are you using?

v0.12.2

## Which operating system are you using?

Ubuntu 20.04LTS

## Describe the problem

We are the developers of Larix Broadcaster app for Android (https://play.google.com/store/apps/details?id=com.wmspanel.larix_broadcaster) and one of our users has complained that Larix fails to publish to simple-server.
We publish 1280х720 h264 video, Larix connects and then disconnects after a few seconds. Then tries again and disconnects again.

Here is server log for this event:
2020/11/26 13:14:10 [0/0/0] rtsp-simple-server v0.12.2
2020/11/26 13:14:10 [0/0/0] [UDP/RTP server] opened on :8000
2020/11/26 13:14:10 [0/0/0] [UDP/RTCP server] opened on :8001
2020/11/26 13:14:10 [0/0/0] [TCP server] opened on :8554
2020/11/26 13:14:11 [1/0/0] [client 192.168.1.132:42242] connected
2020/11/26 13:14:11 [1/0/0] [client 192.168.1.132:42242] OPTIONS
2020/11/26 13:14:11 [1/0/0] [client 192.168.1.132:42242] ANNOUNCE
2020/11/26 13:14:11 [1/0/0] [client 192.168.1.132:42242] SETUP
2020/11/26 13:14:11 [1/0/0] [client 192.168.1.132:42242] SETUP
2020/11/26 13:14:11 [1/0/0] [client 192.168.1.132:42242] RECORD
2020/11/26 13:14:11 [1/1/0] [client 192.168.1.132:42242] is publishing to path 'ch9', 2 tracks with tcp
2020/11/26 13:14:24 [0/0/0] [client 192.168.1.132:42242] disconnected

Here is what we see on Larix side
2020-11-26 12:51:56.196 19408-20211/com.wmspanel.larix_broadcaster D/TcpConnection: Connect
2020-11-26 12:51:56.207 19408-19408/com.wmspanel.larix_broadcaster D/MainActivityBase: onConnectionStateChanged, connectionId=1, state=INITIALIZED, status=SUCCESS
2020-11-26 12:51:56.208 19408-19408/com.wmspanel.larix_broadcaster D/MainActivityBase: onConnectionStateChanged, connectionId=1, state=CONNECTED, status=SUCCESS
2020-11-26 12:51:56.212 19408-20211/com.wmspanel.larix_broadcaster D/RtspParser: status_code=200
2020-11-26 12:51:56.213 19408-20211/com.wmspanel.larix_broadcaster D/RtspParser: status_text=OK
2020-11-26 12:51:56.213 19408-20211/com.wmspanel.larix_broadcaster D/RtspParser: CSeq: 1
2020-11-26 12:51:56.213 19408-20211/com.wmspanel.larix_broadcaster D/RtspParser: Public: GET_PARAMETER, DESCRIBE, ANNOUNCE, SETUP, PLAY, RECORD, PAUSE, TEARDOWN
2020-11-26 12:51:56.214 19408-19408/com.wmspanel.larix_broadcaster D/MainActivityBase: onConnectionStateChanged, connectionId=1, state=SETUP, status=SUCCESS
2020-11-26 12:51:56.220 19408-20211/com.wmspanel.larix_broadcaster D/RtspParser: status_code=200
2020-11-26 12:51:56.220 19408-20211/com.wmspanel.larix_broadcaster D/RtspParser: status_text=OK
2020-11-26 12:51:56.220 19408-20211/com.wmspanel.larix_broadcaster D/RtspParser: CSeq: 2
2020-11-26 12:51:56.224 19408-20211/com.wmspanel.larix_broadcaster D/RtspParser: status_code=200
2020-11-26 12:51:56.224 19408-20211/com.wmspanel.larix_broadcaster D/RtspParser: status_text=OK
2020-11-26 12:51:56.225 19408-20211/com.wmspanel.larix_broadcaster D/RtspParser: CSeq: 3
2020-11-26 12:51:56.225 19408-20211/com.wmspanel.larix_broadcaster D/RtspParser: Session: 12345678
2020-11-26 12:51:56.225 19408-20211/com.wmspanel.larix_broadcaster D/RtspParser: Transport: RTP/AVP/TCP;interleaved=0-1
2020-11-26 12:51:56.229 19408-20211/com.wmspanel.larix_broadcaster D/RtspParser: status_code=200
2020-11-26 12:51:56.229 19408-20211/com.wmspanel.larix_broadcaster D/RtspParser: status_text=OK
2020-11-26 12:51:56.229 19408-20211/com.wmspanel.larix_broadcaster D/RtspParser: CSeq: 4
2020-11-26 12:51:56.229 19408-20211/com.wmspanel.larix_broadcaster D/RtspParser: Session: 12345678
2020-11-26 12:51:56.230 19408-20211/com.wmspanel.larix_broadcaster D/RtspParser: Transport: RTP/AVP/TCP;interleaved=2-3
2020-11-26 12:51:56.233 19408-20211/com.wmspanel.larix_broadcaster D/RtspParser: status_code=200
2020-11-26 12:51:56.233 19408-20211/com.wmspanel.larix_broadcaster D/RtspParser: status_text=OK
2020-11-26 12:51:56.233 19408-20211/com.wmspanel.larix_broadcaster D/RtspParser: CSeq: 5
2020-11-26 12:51:56.234 19408-20211/com.wmspanel.larix_broadcaster D/RtspParser: Session: 12345678
2020-11-26 12:51:56.234 19408-19408/com.wmspanel.larix_broadcaster D/MainActivityBase: onConnectionStateChanged, connectionId=1, state=RECORD, status=SUCCESS
2020-11-26 12:52:06.473 19408-19408/com.wmspanel.larix_broadcaster D/MainActivityBase: onConnectionStateChanged, connectionId=1, state=DISCONNECTED, status=UNKNOWN_FAIL
2020-11-26 12:52:06.475 19408-20211/com.wmspanel.larix_broadcaster E/TcpConnection: java.nio.channels.CancelledKeyException
        at sun.nio.ch.SelectionKeyImpl.ensureValid(SelectionKeyImpl.java:73)
        at sun.nio.ch.SelectionKeyImpl.readyOps(SelectionKeyImpl.java:87)
        at java.nio.channels.SelectionKey.isWritable(SelectionKey.java:312)
        at com.wmspanel.libstream.TcpConnection.processEvent(TcpConnection.java:469)
        at com.wmspanel.libstream.ConnectionManager$1.run(ConnectionManager.java:100)

So somethings' wrong inside the server, could you please check?

Thank you.

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Hello, i regularly use Larix on iOS and it works well, even if RTP interleaved frames sent by Larix have a content with size bigger than the one allowed by UDP MTU (1460 bytes), and this makes difficult routing Larix-originated streams with UDP.

**Comment by aler9** [comment]
Hello, i regularly use Larix on iOS and it works well, even if interleaved frames sent by Larix doesn't seem to have a limit on the content size, and some packets have a content with size bigger than the one allowed by the UDP MTU (1460 bytes), and this makes routing Larix-originated streams with UDP very difficult.
For instance, one could start a stream from iOS, publish it to rtsp-simple-server and then read it with UDP, the latter can be done only if the client supports receiving UDP fragmented packets, which is non-standard and inefficient, and anyway works only if the packet has a size < 65535.
In my opinion, to avoid compatibility issues, you should split H264 frames (NALU frames) into multiple RTP packets, each with a content not bigger than 1460 bytes, like the specification does, and like i do in my encoder, here:
https://github.com/aler9/gortsplib/blob/master/pkg/rtph264/encoder.go#L56

Regarding Android, i'll test as soon as i can.

**Comment by aler9** [comment]
Hello, i checked and it appears that the Android version of Larix disconnects from the server every time it receives RTCP receiver reports. The server sends receiver reports to publishers every 10 seconds.

This is a `rtsp-simple-server` receiver report that causes the app to disconnect:
```
0000   24 03 00 20
0000   81 c9 00 07 f0 c5 34 1e 5a 27 cb 4b 00 00 00 00
0010   00 00 01 d5 00 00 00 00 a3 3d af e0 00 00 00 00
```

parsed
```
RTSP Interleaved Frame, Channel: 0x03, 32 bytes
Real-time Transport Control Protocol (Receiver Report)
    10.. .... = Version: RFC 1889 Version (2)
    ..0. .... = Padding: False
    ...0 0001 = Reception report count: 1
    Packet type: Receiver Report (201)
    Length: 7 (32 bytes)
    Sender SSRC: 0xf0c5341e (4039455774)
    Source 1
        Identifier: 0x5a27cb4b (1512557387)
        SSRC contents
            Fraction lost: 0 / 256
            Cumulative number of packets lost: 0
        Extended highest sequence number received: 469
            Sequence number cycles count: 0
            Highest sequence number received: 469
        Interarrival jitter: 0
        Last SR timestamp: 2738728928 (0xa33dafe0)
        Delay since last SR timestamp: 0 (0 milliseconds)
    [RTCP frame length check: OK - 32 bytes]
```

It is sent after Larix sends a RTCP sender report:
```
0000   24 03 00 1c
0000   80 c8 00 06 5a 27 cb 4b e3 6a a3 33 a7 ef 9d b2
0010   01 45 92 b3 00 00 00 00 00 00 00 00
```

Parsed:
```
RTSP Interleaved Frame, Channel: 0x03, 28 bytes
    Magic: 0x24
    Channel: 0x03
    Length: 28
Real-time Transport Control Protocol (Sender Report)
    10.. .... = Version: RFC 1889 Version (2)
    ..0. .... = Padding: False
    ...0 0000 = Reception report count: 0
    Packet type: Sender Report (200)
    Length: 6 (28 bytes)
    Sender SSRC: 0x5a27cb4b (1512557387)
    Timestamp, MSW: 3815416627 (0xe36aa333)
    Timestamp, LSW: 2817498546 (0xa7ef9db2)
    [MSW and LSW as NTP timestamp: Nov 26, 2020 21:57:07.655999999 UTC]
    RTP timestamp: 21336755
    Sender's packet count: 0
    Sender's octet count: 0
    [RTCP frame length check: OK - 28 bytes]
```

Please check in the app where's the problem, and tell me if i have to change something in the server.

**Comment by WMSPanel** [comment]
We fixed RTCP receiver report processing in Larix for Android.
Our maxNalUnitLen was 20Kb, you can try this version with maxNalUnitLen reduced to 1460:
https://www.dropbox.com/s/lfovt76a2y7zgm9/Larix_maxNalUnitLen1460.apk?dl=0
Let us know how it works for you.

**Comment by sergeiignatov** [comment]
@aler9 Please use this apk https://www.dropbox.com/s/5yzvvacsaf30wr2/larix-rtsp-simple-server.apk?dl=0 to test.

**Comment by aler9** [comment]
@sergeiignatov hello, i've tested the second APK and in my opinion both problems are solved.
The maximum RTP payload size i've seen is 1446 bytes, you can even take it up to 1460 if you want, since

1514 (maximum MTU) -
14 (ethernet header and checksum) - 
20 (IP Header) - 
8 (UDP Header) -
12 (RTP Header) =
1460

I've tested between two pc connected to a wlan, and a single byte more causes fragmentation.

**Comment by WMSPanel** [comment]
Thank you for your feedback. We'll release this fix into production hopefully in 2-3 weeks with other changes after proper testing.

**Comment by kuzzmi** [comment]
@WMSPanel Not sure if that's a known issue for you, but Larix Screencaster still can't publish stream to rtsp-simple-server:

```
2021/01/18 01:34:35 [I] [1/1/0] [client 192.168.88.2:42610] ERR: frame length greater than maximum allowed (10616 vs 2048)
2021/01/18 01:34:35 [I] [0/0/0] [client 192.168.88.2:42610] disconnected
```

**Comment by WMSPanel** [comment]
@kuzzmi We haven't yet propagated that fix to Screencaster.
