### ISSUE TITLE
Segfault after disallowed publish IP

### ISSUE THREAD

**Issue by iSchluff** [aler9/rtsp-simple-server#142]
## Which version are you using?

v0.12.2 and master

## Which operating system are you using?

Linux

## Describe the problem

If I use rtsp-simple-server with publishIPs set, pushing from localhost ipv6 ("::1") will produce a segfault.

```
paths:
  all:
    # ips or networks (x.x.x.x/24) allowed to publish.
    publishIps: ["127.0.0.0/8"]
```

```
2020/12/06 20:33:18 [0/0/0] rtsp-simple-server v0.0.0
2020/12/06 20:33:18 [0/0/0] [UDP/RTP server] opened on :8002
2020/12/06 20:33:18 [0/0/0] [UDP/RTCP server] opened on :8003
2020/12/06 20:33:18 [0/0/0] [TCP server] opened on :8554
2020/12/06 20:33:26 do accept
2020/12/06 20:33:26 [1/0/0] [client [::1]:57928] connected
2020/12/06 20:33:26 [1/0/0] [client [::1]:57928] OPTIONS
2020/12/06 20:33:26 [1/0/0] [client [::1]:57928] ANNOUNCE
2020/12/06 20:33:26 [1/0/0] [client [::1]:57928] ERR: ip '::1' not allowed
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x6f7a7a]

goroutine 21 [running]:
github.com/aler9/gortsplib/pkg/auth.(*Server).GenerateHeader(0x0, 0xc000098450, 0x9580b4, 0x4)
        /home/anton/go/pkg/mod/github.com/aler9/gortsplib@v0.0.0-20201206191443-7b66c8415cbf/pkg/auth/server.go:47 +0x3a
github.com/aler9/rtsp-simple-server/internal/client.(*Client).Authenticate(0xc0000b0000, 0xc00020e680, 0x2, 0x2, 0xc0002048e0, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
        /home/anton/rtsp-simple-server/internal/client/client.go:252 +0x9b7
github.com/aler9/rtsp-simple-server/internal/pathman.(*PathManager).run(0xc00026c000)
        /home/anton/rtsp-simple-server/internal/pathman/pathman.go:176 +0x932
created by github.com/aler9/rtsp-simple-server/internal/pathman.New
        /home/anton/rtsp-simple-server/internal/pathman/pathman.go:80 +0x287
```

**Comment by aler9** [comment]
Hello, thanks for reporting the issue, the problem has been fixed and a unit test has been added not to make this happen again.

**Comment by aler9** [comment]
added to v0.13.0
