### ISSUE TITLE
panic: interface conversion: *core.sourceRedirect is not core.publisher: missing method close

### ISSUE THREAD

**Issue by DonKingMat** [aler9/rtsp-simple-server#933]
## Which version are you using?
v0.18.1

## Which operating system are you using?
```
root@rtsp:~/rtsp# uname -a
Linux rtsp 5.10.92-v8+ #1514 SMP PREEMPT Mon Jan 17 17:39:38 GMT 2022 aarch64 GNU/Linux
```
- [x] Linux arm64 Docker

## Describe the issue

Wanna use the REDIRECT option (server A) like:
```
  a:
    source: redirect
    sourceRedirect: rtsp://my.fancy.domain/a?user=a&pass=a
```

Where on the "other server" (the next one / the destination one / server B) the config is like:
```
  a:
    publishUser: a
    publishPass: a
    readUser: a
    readPass: a
```

## Describe how to replicate the issue
Start both server
Server A (with the problem) which is Raspberry (latest) ARM64:
```
root@rtsp:~/rtsp# ./rtsp-simple-server
2022/04/30 20:51:29 INF rtsp-simple-server v0.18.1
2022/04/30 20:51:29 INF [RTSP] listener opened on :8554 (TCP), :8000 (UDP/RTP), :8001 (UDP/RTCP)
2022/04/30 20:51:29 INF [RTMP] listener opened on :1935
2022/04/30 20:51:29 INF [HLS] listener opened on :8888

```
Server B (which is the my.fancy.domain one on DOCKER):
```
2022/04/30 18:51:10 INF rtsp-simple-server v0.17.17
2022/04/30 18:51:10 INF [RTSP] listener opened on :8554 (TCP), :8000 (UDP/RTP), :8001 (UDP/RTCP)
2022/04/30 18:51:10 INF [RTMP] listener opened on :1935
2022/04/30 18:51:10 INF [HLS] listener opened on :8888
```

Now start RTMP Streaming on Apple iOS application "LITCHI for DJI drones for iOS, version 2.14.0 (3099)" 

## Now I start a RTMP Stream to:
`rtmp://10.11.12.192/a` (where this IP is serverA i can reach without any problem when I do NOT use REDIRECT!)

The error message on server A is now:
```
2022/04/30 20:51:38 INF [RTMP] [conn 10.11.12.120:61802] opened
2022/04/30 20:51:38 INF [path a] closing existing publisher
panic: interface conversion: *core.sourceRedirect is not core.publisher: missing method close

goroutine 35 [running]:
github.com/aler9/rtsp-simple-server/internal/core.(*path).handlePublisherAnnounce(0x4000342d00, {{0x860f90, 0x40000ba000}, {0x40000c20a9, 0x1}, 0x40000ae300, 0x40000aa180})
        /s/internal/core/path.go:776 +0xfc
github.com/aler9/rtsp-simple-server/internal/core.(*path).run.func2(0x4000342d00)
        /s/internal/core/path.go:422 +0x728
github.com/aler9/rtsp-simple-server/internal/core.(*path).run(0x4000342d00)
        /s/internal/core/path.go:457 +0x240
created by github.com/aler9/rtsp-simple-server/internal/core.newPath
        /s/internal/core/path.go:307 +0x5c0
```

Totally not understood ...

The sourceing software is LITCHI for DJI drones for iOS
In my LAB
- The drone has IP 10.11.12.120
- The RasPi server A has 10.11.12.192
- The Docker server B has a Internet IP but did not recognize any connect!!!!

**Comment by aler9** [comment]
Thanks for reporting this issue, this is indeed a bug and will be fixed, but in my opinion you're using an invalid configuration.

From my understanding, you want to publish a stream from a DJI drone to a server hosted on a Raspberry Pi, and then to a server hosted on the cloud, in order to access the stream from the internet:

drone --> raspberry --> cloud

In order to do so, configure the Raspberry Pi instance in this way:

```yml
paths:
  a:
    runOnReady: ffmpeg -i rtsp://localhost:8554/a -c copy -f rtsp rtsp://my.fancy.domain:8554/a
```

In this way, the Raspberry Pi will re-publish any stream published to path `/a` to the remote instance.

You can publish to `rtmp://raspberry-pi/a` and you will be able to read the stream from both `rtmp://raspberry-pi/a` and `rtmp://my.fancy.domain/a`.

The `redirect` parameter is used to redirect RTSP readers from a server to another, and it works exactly like an HTTP redirect: it sends the user a 301 code, it doesn't perform proxing.

**Comment by aler9** [comment]
added in v0.18.3.
